### ISSUE TITLE
[st] Fix image preview

### ISSUE THREAD

**Issue by juliusHuelsmann** [juliusHuelsmann/st#15]
Debug and fix image preview (reoccurring)

**Comment by paretje** [comment]
I just noticed this bug report. I fixed this earlier this evening, based on an old commit from upstream, which has been reverted.
https://github.com/paretje/st/commit/257f0ee7c371543d19da34484f6d67b9d84dc934

For me, this patch works perfectly.  It might be that this is bad for scrolling performance as mentioned in the reverting commit, but I can't say it has bothered me (I haven't noticed anything yet ...) up till now.

**Comment by juliusHuelsmann** [comment]
Thanks for the info, that seems to work for me, too :)

**Comment by paretje** [comment]
There are some glitches I discovered by now, like the cursor isn't always properly visualised, and some glitches in the border after a window resize. I've fixed the cursor now, I'll open a new PR later ;)
