### ISSUE TITLE
VIM: Page up + down

### ISSUE THREAD

**Issue by juliusHuelsmann** [juliusHuelsmann/st#9]
* [ ] Implement page up / down as Ctrl+{f,b} 
* [ ] In order to do this, move the code chunk that is responsible to sort out the current vim motion kpressNormalMode from st.{c,h} to x.c; only issue calls to subroutines in st.c from there. This is necessary in order to have access to the x header files / xkey.

Branch: plainVimPatchV1

**Comment by paretje** [comment]
Related to this: Ctrl-{u,d} would be nice as well, I really miss these at the moment.
